python ./generate_trajtorys.py --name_id 0  > log_0 &  
python ./generate_trajtorys.py --name_id 1  > log_1 &
python ./generate_trajtorys.py --name_id 2  > log_2 &
python ./generate_trajtorys.py --name_id 3  > log_3 &
python ./generate_trajtorys.py --name_id 4  > log_4 &
python ./generate_trajtorys.py --name_id 5  > log_5 &
python ./generate_trajtorys.py --name_id 6  > log_6 &
python ./generate_trajtorys.py --name_id 7  > log_7 &
python ./generate_trajtorys.py --name_id 8  > log_8 &
python ./generate_trajtorys.py --name_id 9  > log_9 &
python ./generate_trajtorys.py --name_id 10 > log_10 & 
python ./generate_trajtorys.py --name_id 11 > log_11 &
python ./generate_trajtorys.py --name_id 12 > log_12 &
python ./generate_trajtorys.py --name_id 13 > log_13 &
python ./generate_trajtorys.py --name_id 14 > log_14 &
python ./generate_trajtorys.py --name_id 15 > log_15 &
python ./generate_trajtorys.py --name_id 16 > log_16 &
python ./generate_trajtorys.py --name_id 17 > log_17 &
python ./generate_trajtorys.py --name_id 18 > log_18 &
python ./generate_trajtorys.py --name_id 19 > log_19 &